sudo: required
dist: xenial
language: c

compiler: gcc

before_install:
  - sudo apt-get --yes update
  - sudo apt-get --yes install libmotif-common libmotif-dev libxpm-dev libxaw7-dev
  - sudo apt-get --yes install xfonts-base libssl-dev

install:
  - sudo ac-tools/bootstrap
  - sudo ./configure -q --enable-ssl --disable-dependency-tracking
  - sudo make -s -j`nproc` && sudo make -s install
  - sudo AFD_WORK_DIR=/root/local afd -a


script: sleep 10 && ps | grep -q afd
