name: CI

on: 
  schedule:
    - cron: "51 09 * * *"
jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: GitHub Sync to Upstream Repository
      uses: mheene/sync-upstream-repo@v0.1.2
      with:
      # GitHub public repo slug or full https clone url (with access_token if needed)
        upstream_repo: https://github.com/holger24/AFD.git
        
